#!/usr/bin/env bash
help_string="edit nextcloud config.php"
CFGFILE="/var/www/nextcloud/config/config.php"
if [ ! -z $CFGFILE ]; then
        vim ${CFGFILE}
else
        echo "### MISSING LOGFILE: ${CFGFILE}"
        exit 1
fi

