#!/usr/bin/env bash
help_string="Parse and list nextcloud audit.log entries"
LOGFILE="/var/log/nextcloud/audit.log"
if [ ! -z $LOGFILE ]; then
	jq -r '[.time,.remoteAddr,.user,.method,.message] | @text' ${LOGFILE}
else
        echo "### MISSING LOGFILE: ${LOGFILE}"
        exit 1
fi

