#!/usr/bin/bash
help_string="Parse and list nextcloud.log entries"

### PRETTY OUTPUT
if [ "$1" == "-p" ]; then
	jq  '. | select(.message|type=="string")' /var/log/nextcloud/nextcloud.log | jq -r '[.time,.remoteAddr,.message] | @text'
else
	jq . /var/log/nextcloud/nextcloud.log
	echo "### TRY RUNNING showlog -p"
fi
