#!/usr/bin/env bash
help_string="Show mysql slow.log entries"
LOGFILE="/var/log/mysql/slow.log"
if [ ! -z $LOGFILE ]; then
	tail -20f /var/log/mysql/slow.log
else
	echo "### MISSING LOGFILE: ${LOGFILE}"
	exit 1
fi
