#!/usr/bin/bash
help_string="Show failed logins from nextcloud.log"
jq -r '. | select(.message|type=="string") | select(.message | contains("Login"))' /var/log/nextcloud/nextcloud.log | jq -r '[.time,.message,.userAgent] | @text'
